
truncate table [dbo].[nodes_stars]

INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Steve Rogers / Captain America','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Tony Stark / Iron Man','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Bruce Banner / Hulk','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Jarvis / Vision','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Natasha Romanoff / Black Widow','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('James Rhodes / War Machine','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Sam Wilson / Falcon','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Bucky Barnes / Winter Soldier','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Clint Barton / Hawkeye','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Wanda Maximoff / Scarlet Witch','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Scott Lang / Ant-Man','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Pietro Maximoff / Quicksilver','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Hope van Dyne / Vasp?','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Thor','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Dr. Stephen Strange','avenger')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('T''Challa','avenger')

INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Peter Quill','guardian')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Gamora','guardian')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Drax','guardian')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Groot','guardian')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Rocket','guardian')

INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Dr. Hank Pym','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Janet Van Dyne','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('The Ancient One','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Wong','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Clea?','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('General ''Thunderbolt'' Ross','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('The Collector','undefined')

INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Nick Fury','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Agent Maria Hill','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Agent Coulson','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Melinda May','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Daisy ''Skye'' Johnson','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Leo Fitz','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Jemma Simmons','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Grant Ward','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Stan Lee','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Erik Selvig','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Pepper Potts','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Lady Sif','undefined')

INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Peggy Carter','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Edwin Jarvis','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Howard Stark','undefined')

INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Matt Murdock','defender')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Karen Page','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Foggy Nelson','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Wilson Fisk','villain')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Frank Castle','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Elektra Natchios','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Stick','undefined')

INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Jessica Jones','defender')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Trish Walker','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Kilgrave','villain')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Jeri Hogarth','undefined')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Luke Cage','defender')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Claire Temple','undefined')

INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Malekith','villain')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Ultron','villain')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Dormammu?','villain')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Baron Mordo','villain')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Loki','villain')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Thanos','villain')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Ronan','villain')
INSERT INTO [dbo].[nodes_stars]([character_n],[type])VALUES('Nebula','villain')


